### PR TITLE
Update core dependency to latest play core review library

### PR DESCRIPTION
**Pull request by ancha3**

### CODE REVIEW

**Comment by LucasClaude** [comment]
+1

**Review by ricardosoaresl — APPROVED** [review]
+1

**Review by LucasClaude — APPROVED** [review]

**Comment by Vinaum8** [comment]
@KjellConnelly bro, how can i use the latest version of this lib? are you going to publish it on npm? do you need any support to create a CI for publishing?

**Comment by gabrielmaldi** [comment]
@KjellConnelly, will this get released in a new version?

**Pull request merged**
