### PR TITLE
Support turbomodules in RNRateModule

### PR DESCRIPTION
**Pull request by janicduplessis**
Turbomodules are the next version of native modules. These changes makes this module compatible.

### CODE REVIEW

**Comment by janicduplessis** [comment]
@KjellConnelly Any chance you could have a look at this?

**Comment by KjellConnelly** [comment]
I'm not sure of the implications of turbo modules, but it looks like they will be used somewhere around the end of this year. The react-native github page uses this sort of syntax for their own android modules, so I'm just going to merge and cross my fingers that it doesn't break anything. I believe `androidX` must be used. But who knows....

**Comment by janicduplessis** [comment]
@KjellConnelly The module annotation has existed for a few years, it is just not yet used. I've added it to many projects without issues so it should be fine :)

**Comment by KjellConnelly** [comment]
Ya I was googling it and saw it's been talked about for several years. Just looks like there hasn't been a full implementation yet as the RN docs still show the old way.

**Pull request merged**
